#define MULTIBOOT_HEADER_MAGIC          0x1BADB002 // 必ず必要なマジックヘッダ
#define MULTIBOOT_HEADER_FLAGS          0x00000000 // 必ず必要なフラグ
#define MULTIBOOT_HEADER_CHECKSUM       -(MULTIBOOT_HEADER_MAGIC+MULTIBOOT_HEADER_FLAGS)
#define KERNEL_STACK_SIZE               0x100000 // 
